spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

data:
  mongodb:
    host: localhost
    port: 27017
    database: testdb


    redis:
      host: localhost
      port: 6379
      password: <your_password_if_any>  # Nếu có password
      timeout: 2000  # timeout kết nối (millisecond)
      jedis: # Sử dụng Jedis nếu cần cấu hình cho client Redis
        pool:
          max-active: 10  # Số lượng kết nối tối đa
          max-wait: 2000  # Thời gian tối đa chờ kết nối
          min-idle: 1  # Số lượng kết nối tối thiểu
          max-idle: 5  # Số lượng kết nối idle tối đa
